### ISSUE TITLE
Dev docs?

### ISSUE THREAD

**Issue by ksorv** [jamesctucker/teach-yourself-code#9]
I'm unable to set it up locally, I'd suggest you to work on those docs first!

So, we can help you handle the rest.

**Comment by sanvishal** [comment]
+1 I am puzzled about what "AUTH0_DOMAIN" does. I've set up everything other than that.

**Comment by jamesctucker** [comment]
Good point - I'll write up detailed local set-up instructions today. Please bear with me as this is the first time I've asked the community to contribute to a project!

**Comment by jamesctucker** [comment]
@ksorv @sanvishal I updated the readme with additional set-up instructions. Please let me know if they are unclear or seem incomplete still.

**Comment by ksorv** [comment]
Well, It's first time me. I know how to work around things! And I know you're pretty awesome with the things you do. Instead of YT tuts I'm here, learning from you. Hope It's gonna go big with us.

**Comment by jamesctucker** [comment]
@ksorv I'm completely fine with keeping this open for now!

And glad to have you be a part of this! Eager to learn from you as well, struggle through this together, and see what comes out of this project!

**Comment by ksorv** [comment]
@jamesctucker 

I'm updating the docs with some more info.

I still can't find where to run the SQL schema(in the hasura console)?

**Comment by sanvishal** [comment]
I think it's in the "Data" tab after you deploy your own graphql server using heroku.

**Comment by ksorv** [comment]
Wasn't looking too carefully!

**Comment by sanvishal** [comment]
@jamesctucker 

I keep getting errors because playlists are not getting fetched properly. I checked the **Networks** tab in dev tools for graphql requests and `fetchPlaylists` is returning...
`message: "field "topic" not found in type: 'playlists_bool_exp'"`

Do I have to fill the database with some playlists? graphql noob here 😅

**Comment by ksorv** [comment]
I'd suggest you create another issue!

**Comment by jamesctucker** [comment]
@ksorv Does this help with knowing where to enter the SQL?

![image](https://user-images.githubusercontent.com/43385166/81213152-98886580-8f9b-11ea-9bcc-8d8987ea67fb.png)

**Comment by ksorv** [comment]
I actually got that already. Thaks tho
